name: 'Pattini app'
description: 'Rewards an external contributor'
author: 'W3HC'

branding:
  icon: 'arrow-right-circle'
  color: 'blue'

inputs:
  ISSUE_NUMBER:
    description: 'The issue number to reward.'
    required: true
  PRIVATE_KEY:
    description: 'The private key to use to authenticate with GitHub'
    required: true


runs:
  using: node20
  main:  |
  echo "Running the action..."
  echo '{{inputs.PRIVATE_KEY}}'
      
