name: 'Pattini app'
description: 'Rewards an external contributor'
author: 'W3HC'

branding:
  icon: 'arrow-right-circle'
  color: 'blue'

on:
  workflow_call:
    inputs:
      issue_number:
        description: 'The issue number to reward.'
        required: true
      private_key:
        description: 'The private key to use to authenticate with GitHub'
        required: true

jobs:
  get input:
    runs-on: ubuntu-latest

    runs:
      using: node20
      main:  |
        echo ${{ inputs }}
        echo ${{ inputs.issue_number }}
        echo ${{ github.event }}

      
