name: 'PattiniApp'
description: 'Rewards an external contributor'
author: 'W3HC'

branding:
  icon: 'arrow-right-circle'
  color: 'blue'

inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
