name: 'Pattini app'
description: 'Rewards an external contributor'
author: 'W3HC'

branding:
  icon: 'arrow-right-circle'
  color: 'blue'

inputs:
  ISSUE_NUMBER:
    description: 'The issue number to reward.'
    required: true
  PULL_REQUEST_NUMBER:
    description: 'The pull request number to reward.'
    required: true
  PRIVATE_KEY:
    description: 'The private key to use to authenticate with GitHub'
    required: true
  ACTION:
    description: 'The action to perform'
    required: true


runs:
  using: node20
  main: dist/index.js

      
