name: 'Pattini app'
description: 'Rewards an external contributor'
author: 'W3HC'

branding:
  icon: 'arrow-right-circle'
  color: 'blue'

inputs:
  issue_number:
    description: 'The issue number to reward'
    required: true
  private_key:
    description: 'The private key to use to authenticate with GitHub'
    required: true

runs:
  using: node20
  main: |
  echo ${{ github.event.inputs.issue_number }}
  echo ${{ github.event.inputs.private_key }}
  dist/index.js 

  
