name: 'Pattini app'
description: 'Rewards an external contributor'
author: 'W3HC'

branding:
  icon: 'https://bafkreid47g4uxs5msarp3v5hvf7ssdqi3la5kylmwseirva7wzkyc5bgvi.ipfs.w3s.link/'

inputs:
  PRIVATE_KEY:
    description: 'The private key of the owner wallet'
    required: true
  REPOSITORY:
    description: 'The repository to use'
    required: true
  ACTION:
    description: 'The action to perform'
    required: true
  ISSUE_NUMBER:
    description: 'The issue number to reward.'
    required: true
  PULL_REQUEST_NUMBER:
    description: 'The pull request number to reward.'
    required: false
  GITHUB_TOKEN:
    description: 'The GitHub token to use'
    required: false

runs:
  using: node20
  main: dist/index.js
